language: node_js

node_js:
  - "12"
  
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/waiter_test

before_script:
  - psql -c 'create database  waiter_test;' -U postgres
  - psql -U postgres -d waiter_test -a -f tables.sql

services:
  - postgresql